# Generated by Django 6.0.3 on 2026-03-22 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('sinopse', models.TextField()),
                ('duracao', models.IntegerField()),
                ('em_cartaz', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('colunas', models.PositiveIntegerField(default=10)),
                ('fileiras', models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_inicio', models.DateTimeField()),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='reserve.filme')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.sala')),
            ],
        ),
        migrations.CreateModel(
            name='AssentoReservado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileira', models.CharField(max_length=2)),
                ('coluna', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('R', 'Reservado'), ('P', 'Pago')], default='R', max_length=20)),
                ('data_reserva', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reserve.sessao')),
            ],
            options={
                'unique_together': {('sessao', 'fileira', 'coluna')},
            },
        ),
    ]
